export const resumeData = {
  ar: {
    pageTitle: "╪¡╪│┘è┘å ╪º┘ä┘ê┘è╪│┘è | ┘à┘ç┘å╪»╪│ ╪¿╪▒┘à╪¼┘è╪º╪¬ .NET",
    hero: {
      name: "╪¡╪│┘è┘å ╪º┘ä┘ê┘è╪│┘è",
      brandMark: "╪¡",
      brandTagline: "┘à┘ç┘å╪»╪│ ╪¿╪▒┘à╪¼┘è╪º╪¬ .NET",
      footerRole: "┘à┘ç┘å╪»╪│ ╪¿╪▒┘à╪¼┘è╪º╪¬ .NET",
      title: "┘à┘ç┘å╪»╪│ ╪¿╪▒┘à╪¼┘è╪º╪¬ .NET",
      location: "╪Ñ╪▒╪¿╪»╪î ╪º┘ä╪ú╪▒╪»┘å",
      availability: "┘à╪¬╪º╪¡ ┘ä┘ü╪▒╪╡ .NET ╪¿╪»┘ê╪º┘à ┘â╪º┘à┘ä",
      metaLabels: { location: "╪º┘ä┘à┘ê┘é╪╣", availability: "╪º┘ä╪¬┘ê┘ü╪▒" },
      bio: "┘à┘ç┘å╪»╪│ ╪¿╪▒┘à╪¼┘è╪º╪¬ ╪»┘é┘è┘é ┘è╪¿┘å┘è ╪¬╪╖╪¿┘è┘é╪º╪¬ ┘ê┘è╪¿ ┘ê╪│╪╖╪¡ ┘à┘â╪¬╪¿ ╪ó┘à┘å╪⌐ ┘ê┘é╪º╪¿┘ä╪⌐ ┘ä┘ä╪¬┘ê╪│╪╣ ╪╢┘à┘å ┘à┘å╪╕┘ê┘à╪⌐ Microsoft .NET ┘à╪╣ ╪¬╪▒┘â┘è╪▓ ╪╣┘ä┘ë ╪º┘ä╪ú┘å╪╕┘à╪⌐ ╪º┘ä┘à╪º┘ä┘è╪⌐╪î ╪ú╪»┘ê╪º╪¬ ╪º┘ä┘à┘ê╪º╪▒╪» ╪º┘ä╪¿╪┤╪▒┘è╪⌐╪î ┘ê╪ú╪¬┘à╪¬╪⌐ ╪¬┘é╪º╪▒┘è╪▒ Crystal Reports.",
      cvUrl: "assets/HusseinAlwisiResume.pdf",
      ctas: { primary: "╪¡┘à┘æ┘ä ╪º┘ä╪│┘è╪▒╪⌐ ╪º┘ä╪░╪º╪¬┘è╪⌐", secondary: "┘ä┘å╪¬╪¡╪»╪½" },
      photo: "assets/Me.jpeg",
      photoAlt: "╪╡┘ê╪▒╪⌐ ╪¡╪│┘è┘å ╪º┘ä┘ê┘è╪│┘è",
      chips: [
        "C# / VB.NET / .NET",
        "WinForms ┘ê DevExpress",
        "ASP.NET MVC / WebForms",
        "SQL Server ┘ê Entity Framework",
        "╪ú╪¬┘à╪¬╪⌐ Crystal Reports",
      ],
      dynamicRoles: ["╪ú╪¿┘å┘è ╪ú╪»┘ê╪º╪¬ ┘à╪¡╪º╪│╪¿┘è╪⌐ ┘à┘ê╪½┘ê┘é╪⌐", "╪ú┘Å╪╖┘ä┘é ╪¬╪╖╪¿┘è┘é╪º╪¬ .NET ┘à╪ñ╪│╪│┘è╪⌐", "╪ú╪ñ╪¬┘à╪¬ ╪º┘ä╪¬┘é╪º╪▒┘è╪▒ ╪º┘ä┘à╪º┘ä┘è╪⌐"],
      clientsHeading: "┘ü╪▒┘é ╪╣┘à┘ä ╪»╪╣┘à╪¬┘ç╪º",
      clients: ["Mozon Accounting", "HR Org Builder", "Attachments", "PureActive"],
      score: 35,
      scoreSuffix: "%",
      scoreLabel: "╪¬╪│╪▒┘è╪╣ ╪º┘ä╪╣┘à┘ä┘è╪º╪¬",
      scoreCaption: "┘à╪¬┘ê╪│╪╖ ╪º┘ä╪¼┘ç╪» ╪º┘ä┘è╪»┘ê┘è ╪º┘ä╪░┘è ╪¬┘à ╪¬┘é┘ä┘è┘ä┘ç ╪»╪º╪«┘ä ╪º┘ä┘à╪│╪º╪▒╪º╪¬ ╪º┘ä╪ú╪│╪º╪│┘è╪⌐",
    },
    copy: {
      nav: {
        ariaLabel: "╪┤╪▒┘è╪╖ ╪º┘ä╪¬┘å┘é┘ä ╪º┘ä╪▒╪ª┘è╪│┘è",
        home: "╪º┘ä╪▒╪ª┘è╪│┘è╪⌐",
        impact: "╪º┘ä╪ú╪½╪▒",
        experience: "╪º┘ä┘à╪│╪º╪▒ ╪º┘ä┘à┘ç┘å┘è",
        skills: "╪º┘ä┘à┘ç╪º╪▒╪º╪¬",
        certificates: "╪º┘ä╪┤┘ç╪º╪»╪º╪¬",
        work: "╪»╪▒╪º╪│╪º╪¬ ╪¡╪º┘ä╪⌐",
        lab: "┘à╪╣┘à┘ä ╪º┘ä╪╣┘à┘ä┘è╪º╪¬",
        contact: "╪¬┘ê╪º╪╡┘ä",
        cta: "╪¬╪¡╪»╪½ ┘à╪╣┘è",
      },
      sections: {
        impact: {
          eyebrow: "┘å╪¬╪º╪ª╪¼ ┘é╪º╪¿┘ä╪⌐ ┘ä┘ä┘é┘è╪º╪│",
          title: "╪ú╪▒┘é╪º┘à ╪¬╪»╪╣┘à ╪º┘ä┘é╪▒╪º╪▒",
          description:
            "┘â┘ä ┘à╪¿╪º╪»╪▒╪⌐ ╪ú╪╣┘à┘ä ╪╣┘ä┘è┘ç╪º ┘à╪▒╪¬╪¿╪╖╪⌐ ╪¿┘à╪ñ╪┤╪▒ ┘ê╪º╪╢╪¡╪¢ ┘à┘å ╪ú╪¬┘à╪¬╪⌐ ╪º┘ä╪¡╪│╪º╪¿╪º╪¬ ╪Ñ┘ä┘ë ╪¿┘ê╪º╪¿╪º╪¬ ╪º┘ä╪╖┘ä╪¿╪⌐. ┘ç╪░┘ç ╪ú╪¡╪»╪½ ╪º┘ä╪ú╪▒┘é╪º┘à ┘à┘å ┘à╪┤╪º╪▒┘è╪╣ ┘à┘ê╪▓┘ê┘å ┘ê┘à╪┤╪º╪▒┘è╪╣ ╪º┘ä╪¼╪º┘à╪╣╪⌐.",
        },
        experience: {
          eyebrow: "╪º┘ä┘à╪│╪º╪▒ ╪º┘ä┘à┘ç┘å┘è",
          title: "╪¬╪│┘ä┘è┘à ╪╣┘à┘ä┘è",
          description:
            "╪ú╪¬┘å┘é┘æ┘ä ╪¿┘è┘å ╪¬╪╖╪¿┘è┘é╪º╪¬ ╪│╪╖╪¡ ╪º┘ä┘à┘â╪¬╪¿ ┘ê╪º┘ä┘ê┘è╪¿╪î ╪ú┘å┘à╪░╪¼ ┘é┘ê╪º╪╣╪» ╪º┘ä╪¿┘è╪º┘å╪º╪¬╪î ╪ú┘ê╪¼┘æ┘ç ┘ü╪▒┘é ╪º┘ä╪º╪«╪¬╪¿╪º╪▒╪î ┘ê╪ú╪│┘ä┘æ┘à ┘à┘å╪¬╪¼╪º╪¬ ┘é╪º╪¿┘ä╪⌐ ┘ä┘ä╪╡┘è╪º┘å╪⌐ ┘ä┘ü┘É╪▒┘é ╪º┘ä╪╣┘à┘ä ╪º┘ä╪»╪º╪«┘ä┘è╪⌐.",
        },
        skills: {
          eyebrow: "┘à╪╡┘ü┘ê┘ü╪⌐ ╪º┘ä┘à┘ç╪º╪▒╪º╪¬",
          title: "╪╣┘à┘é ╪¬┘é┘å┘è + ┘à┘ä┘â┘è╪⌐",
          description: "┘à┘à╪º╪▒╪│╪º╪¬ .NET ╪¡╪»┘è╪½╪⌐╪î ╪º╪│╪¬╪╣┘ä╪º┘à╪º╪¬ SQL ┘à╪¡╪│┘æ┘å╪⌐╪î ┘ê╪╣┘é┘ä┘è╪⌐ ┘à┘å╪¬╪¼ ╪¬┘Å╪¿┘é┘è ╪ú╪╡╪¡╪º╪¿ ╪º┘ä┘à╪╡┘ä╪¡╪⌐ ┘à╪¬┘ê╪º┘ü┘é┘è┘å ┘ê┘ê╪º╪½┘é┘è┘å.",
        },
        certificates: {
          eyebrow: "╪º┘ä╪┤┘ç╪º╪»╪º╪¬",
          title: "╪¬╪╣┘ä┘à ┘à┘ê╪½┘æ┘é",
          description: "┘à╪¼┘à┘ê╪╣╪⌐ ╪»┘ê╪▒╪º╪¬ ┘ê╪┤┘ç╪º╪»╪º╪¬ ╪¬╪╣╪▓┘æ╪▓ ╪╣┘à┘ä┘è ┘ü┘è .NET ┘ê┘é┘ê╪º╪╣╪» ╪º┘ä╪¿┘è╪º┘å╪º╪¬ ┘ê╪º┘ä╪¬┘ê╪º╪╡┘ä.",
          cta: "╪╣╪▒╪╢ ╪º┘ä╪┤┘ç╪º╪»╪⌐",
        },
        work: {
          eyebrow: "╪»╪▒╪º╪│╪º╪¬ ╪¡╪º┘ä╪⌐",
          title: "┘à╪┤╪º╪▒┘è╪╣ ╪¡┘ä╪¬ ╪ú┘ä┘à┘ï╪º ╪¡┘é┘è┘é┘è┘ï╪º",
          description: "╪ú╪╣┘à╪º┘ä ┘à╪«╪¬╪º╪▒╪⌐ ╪¬┘à╪¬╪» ╪¿┘è┘å ╪¡╪▓┘à ┘à╪¡╪º╪│╪¿┘è╪⌐╪î ╪ú╪»┘ê╪º╪¬ ┘à┘ê╪º╪▒╪» ╪¿╪┤╪▒┘è╪⌐╪î ┘ê┘à┘å╪╡╪⌐ ╪╡╪¡╪⌐ ┘ê┘ä┘è╪º┘é╪⌐ ┘à╪¬╪╣╪»╪»╪⌐ ╪º┘ä┘à┘å╪╡╪º╪¬.",
          controls: { prev: "╪º┘ä┘à╪┤╪▒┘ê╪╣ ╪º┘ä╪│╪º╪¿┘é", next: "╪º┘ä┘à╪┤╪▒┘ê╪╣ ╪º┘ä╪¬╪º┘ä┘è" },
          viewProject: "╪╣╪▒╪╢ ╪º┘ä┘à╪┤╪▒┘ê╪╣",
        },
        lab: {
          eyebrow: "┘à╪╣┘à┘ä ╪º┘ä╪╣┘à┘ä┘è╪º╪¬",
          title: "┘â┘è┘ü ╪ú┘é╪»┘æ┘à ╪º┘ä╪¡┘ä┘ê┘ä",
          description: "┘à┘å ╪º┘ä╪º┘â╪¬╪┤╪º┘ü ╪Ñ┘ä┘ë ╪¬╪│┘ä┘è┘à ╪º┘ä╪¼┘ê╪»╪⌐╪î ┘â┘ä ╪«╪╖┘ê╪⌐ ╪¬╪¿┘é┘è ╪ú╪╡╪¡╪º╪¿ ╪º┘ä┘à╪╡┘ä╪¡╪⌐ ┘ü┘è ╪º┘ä╪╡┘ê╪▒╪⌐ ┘ê╪¬╪╢┘à┘å ╪¬╪»┘ü┘é ╪º┘ä╪¿┘è╪º┘å╪º╪¬ ╪Ñ┘ä┘ë ╪º┘ä╪¬┘é╪º╪▒┘è╪▒ ╪º┘ä╪╡╪¡┘è╪¡╪⌐.",
        },
        contact: {
          eyebrow: "┘à╪│╪º╪▒ ╪¬┘ê╪º╪╡┘ä ╪│╪▒┘è╪╣",
          title: "┘ä┘å╪¿╪»╪ú ╪¡╪»┘è╪½┘ï╪º",
          description: "╪¬╪¡╪¬╪º╪¼ ┘à╪╖┘ê╪▒ .NET ┘à┘ê╪½┘ê┘é ┘ä┘à┘å╪¬╪¼┘â ╪º┘ä┘à╪¡╪º╪│╪¿┘è ╪ú┘ê ┘ê╪¡╪»╪⌐ ╪º┘ä┘à┘ê╪º╪▒╪» ╪º┘ä╪¿╪┤╪▒┘è╪⌐╪ƒ ╪┤╪º╪▒┘â┘å┘è ╪º┘ä╪¬┘ü╪º╪╡┘è┘ä ┘ê╪│╪ú╪▒╪» ╪«┘ä╪º┘ä ┘è┘ê┘à.",
        },
      },
      labDetail: { eyebrow: "╪¬┘ü╪º╪╡┘è┘ä ╪º┘ä┘à╪▒╪¡┘ä╪⌐" },
      footer: {
        primary: "┬⌐ {year} ┘â┘ä ╪º┘ä╪¡┘é┘ê┘é ┘à╪¡┘ü┘ê╪╕╪⌐.",
        secondary: "╪ú╪¿┘å┘è ╪¿╪▒┘à╪¼┘è╪º╪¬ ┘ç╪º╪»┘ü╪⌐.",
      },
    },
    stats: [
      {
        label: "╪│┘å┘ê╪º╪¬ ╪º┘ä╪«╪¿╪▒╪⌐ ╪º┘ä╪╣┘à┘ä┘è╪⌐",
        value: 2,
        suffix: "+",
        description: "╪│┘å╪¬╪º┘å ┘à┘å ╪Ñ╪╖┘ä╪º┘é ╪ú┘å╪╕┘à╪⌐ .NET ╪╣╪¿╪▒ ╪º┘ä╪¬┘à┘ê┘è┘ä ┘ê╪º┘ä┘à┘ê╪º╪▒╪» ╪º┘ä╪¿╪┤╪▒┘è╪⌐ ┘ê╪º┘ä╪¬╪╣┘ä┘è┘à.",
      },
      {
        label: "╪¬┘ê┘ü┘è╪▒ ╪Ñ╪╣╪»╪º╪» ╪º┘ä┘é┘è┘ê╪» ╪º┘ä┘è╪»┘ê┘è╪⌐",
        value: 35,
        suffix: "%",
        description: "╪ú╪¬┘à╪¬╪⌐ ┘à╪«╪╖╪╖ ╪º┘ä╪¡╪│╪º╪¿╪º╪¬ ╪»╪º╪«┘ä ╪¼┘å╪º╪¡ ┘à┘ê╪▓┘ê┘å ╪º┘ä┘à╪¡╪º╪│╪¿┘è.",
      },
      {
        label: "╪¬╪│╪▒┘è╪╣ ╪º┘ä╪¬┘é╪º╪▒┘è╪▒ ╪º┘ä┘à╪º┘ä┘è╪⌐",
        value: 30,
        suffix: "%",
        description: "┘é┘ê╪º┘ä╪¿ Crystal Reports ╪º┘ä╪¼╪º┘ç╪▓╪⌐ ┘ä┘ä╪¬╪╡╪»┘è╪▒ ╪¬┘é┘ä┘ä ╪▓┘à┘å ╪º┘ä╪¬╪¡╪╢┘è╪▒ ╪¿╪┤┘â┘ä ┘à╪¿╪º╪┤╪▒.",
      },
      {
        label: "╪¬╪¡╪│┘è┘å ╪│╪▒╪╣╪⌐ ╪º┘ä╪¿╪¡╪½ ┘ü┘è ╪º┘ä┘à┘ê╪º╪▒╪» ╪º┘ä╪¿╪┤╪▒┘è╪⌐",
        value: 30,
        suffix: "%",
        description: "┘à┘Å┘å╪┤╪ª ╪º┘ä┘ç┘è┘â┘ä ╪º┘ä╪¬┘å╪╕┘è┘à┘è ┘è┘à┘â┘æ┘å ╪º┘ä┘à┘ê╪º╪▒╪» ╪º┘ä╪¿╪┤╪▒┘è╪⌐ ┘à┘å ╪Ñ┘è╪¼╪º╪» ╪º┘ä╪ú┘ü╪▒╪º╪» ┘ê╪º┘ä┘ê╪¡╪»╪º╪¬ ╪ú╪│╪▒╪╣ ╪¿┘Ç 30%.",
      },
      {
        label: "╪»┘ê╪▒╪⌐ ┘à╪▒╪º╪¼╪╣╪⌐ ╪º┘ä╪¬╪»╪▒┘è╪¿ ╪ú╪│╪▒╪╣",
        value: 40,
        suffix: "%",
        description: "╪¬╪»┘ü┘é ╪╣┘à┘ä ┘à╪¿┘å┘è ╪╣┘ä┘ë ╪º┘ä╪ú╪»┘ê╪º╪▒ ┘ü┘è ╪¿┘ê╪º╪¿╪⌐ ╪º┘ä╪¬╪»╪▒┘è╪¿ ╪¿┘å╪╕╪º┘à MVC ┘è┘é┘ä┘ä ╪▓┘à┘å ┘à╪▒╪º╪¼╪╣╪⌐ ╪º┘ä╪¬┘é╪º╪▒┘è╪▒ ┘à┘å ╪ú╪│╪º╪¿┘è╪╣ ┘ä╪ú┘è╪º┘à.",
      },
    ],
    experiences: [
      {
        title: "Medu (┘à┘ê╪▓┘ê┘å ┘ä┘ä╪¬╪╣┘ä┘è┘à) - ╪º┘ä┘à╪▒┘ü┘é╪º╪¬ ┘ê╪│┘è╪▒ ╪º┘ä╪╣┘à┘ä",
        company: "Mozon Technology",
        period: "┘è┘ê┘ä┘è┘ê 2025 - ╪»┘è╪│┘à╪¿╪▒ 2025",
        description: "┘é┘Å╪»╪¬ ╪¬╪╖┘ê┘è╪▒ Windows Forms ┘ä┘Ç Medu ┘ä╪Ñ╪»╪º╪▒╪⌐ ╪º┘ä┘à╪▒┘ü┘é╪º╪¬ ┘ê┘à╪│╪º╪▒╪º╪¬ ╪º┘ä┘à┘ê╪º┘ü┘é╪⌐.",
        highlights: [
          "╪¿┘å╪º╪í ╪Ñ╪»╪º╪▒╪⌐ ┘à╪▒┘ü┘é╪º╪¬ ╪ó┘à┘å╪⌐ (╪▒┘ü╪╣╪î ┘à╪╣╪º┘è┘å╪⌐╪î ╪¬┘å╪▓┘è┘ä╪î ╪¡╪░┘ü) ┘ä┘à┘ä┘ü╪º╪¬ ╪º┘ä╪╖┘ä╪¿╪⌐ ┘ê╪º┘ä┘å╪╕╪º┘à.",
          "╪¬╪╖╪¿┘è┘é ╪╡┘ä╪º╪¡┘è╪º╪¬ ┘ä╪ú┘å┘ê╪º╪╣ ╪º┘ä┘à╪│╪¬┘å╪»╪º╪¬╪î ╪¬╪¡╪│┘è┘å ╪º┘ä┘ê╪º╪¼┘ç╪⌐╪î ┘à╪╣╪º┘ä╪¼╪⌐ ┘å╪¬╪º╪ª╪¼ ╪º┘ä╪º╪«╪¬╪¿╪º╪▒╪î ┘ê╪Ñ╪╖┘ä╪º┘é ╪ú╪»┘ä╪⌐ ╪º┘ä╪¬┘ü╪╣┘è┘ä ┘ê╪º┘ä╪¬╪╖┘ê┘è╪▒.",
          "╪¬╪│┘ä┘è┘à ╪ú┘å┘ê╪º╪╣ ╪│┘è╪▒ ╪╣┘à┘ä╪î ┘à┘ê╪º┘ü┘é╪º╪¬╪î ┘ê╪┤╪º╪┤╪º╪¬ ╪╖┘ä╪¿╪º╪¬┘è / ┘à┘ê╪º┘ü┘é╪º╪¬┘è ╪¿┘à╪¡╪▒┘â ┘à┘ê╪º┘ü┘é╪º╪¬ ┘à╪¬╪╣╪»╪» ╪º┘ä╪«╪╖┘ê╪º╪¬ ┘à╪▒┘å.",
        ],
        stack: ["C#", "WinForms", "SQL Server", "Crystal Reports"],
      },
      {
        title: "╪º┘ä┘å╪╕╪º┘à ╪º┘ä┘à╪¡╪º╪│╪¿┘è - ASP.NET Windows Forms",
        company: "Mozon Technology",
        period: "╪»┘è╪│┘à╪¿╪▒ 2024 - ┘à╪º┘è┘ê 2025",
        description: "┘à┘ä┘â╪¬ ╪¬╪╖┘ê┘è╪▒ ╪º┘ä┘ê╪¡╪»╪º╪¬ ╪º┘ä┘à╪¡╪º╪│╪¿┘è╪⌐ ┘ê╪¬╪¡╪│┘è┘å ╪ú╪»╪º╪í ╪º┘ä╪¬┘é╪º╪▒┘è╪▒.",
        highlights: [
          "╪¬╪│┘ä┘è┘à ╪ú┘å┘ê╪º╪╣ ╪º┘ä┘é┘è┘ê╪»╪î ╪Ñ╪»╪«╪º┘ä╪º╪¬ ╪º┘ä┘é┘è┘ê╪»╪î ╪ú┘å┘ê╪º╪╣ ╪º┘ä╪¡╪│╪º╪¿╪º╪¬╪î ┘ê┘à╪«╪╖╪╖ ╪¡╪│╪º╪¿╪º╪¬ ╪»┘è┘å╪º┘à┘è┘â┘è.",
          "╪«┘ü╪╢ ╪º┘ä┘à╪╣╪º┘ä╪¼╪⌐ ╪º┘ä┘è╪»┘ê┘è╪⌐ ╪¿┘å╪│╪¿╪⌐ 35% ╪╣╪¿╪▒ ╪¬╪¡╪│┘è┘å ╪º┘ä┘å┘à╪º╪░╪¼ ┘ê╪▒╪¿╪╖ ┘é╪º╪╣╪»╪⌐ ╪º┘ä╪¿┘è╪º┘å╪º╪¬.",
          "╪»┘à╪¼ SAP Crystal Reports (╪ú╪│╪▒╪╣ 30%) ┘ê╪╢╪¿╪╖ SQL ┘ä╪│╪▒╪╣╪⌐ ╪ú╪╣┘ä┘ë ╪¿┘å╪¡┘ê 20%.",
        ],
        stack: ["C#", "WinForms", "SQL Server", "Crystal Reports"],
      },
      {
        title: "╪¬╪╖┘ê┘è╪▒ ASP.NET WebForms - ╪¬╪»╪▒┘è╪¿",
        company: "Mozon Technology",
        period: "╪│╪¿╪¬┘à╪¿╪▒ - ┘å┘ê┘ü┘à╪¿╪▒ 2024",
        description: "╪¬╪¡╪»┘è╪½ ╪┤╪º╪┤╪º╪¬ ╪º┘ä┘à┘ê╪º╪▒╪» ╪º┘ä╪¿╪┤╪▒┘è╪⌐ ┘ê┘ç┘è┘â┘ä╪⌐ ╪º┘ä╪¿┘è╪º┘å╪º╪¬ ╪ú╪½┘å╪º╪í ╪º┘ä╪¬╪»╪▒┘è╪¿.",
        highlights: [
          "╪¬╪¡╪»┘è╪½ ┘ê╪º╪¼┘ç╪⌐ ╪º┘ä┘à┘ê╪º╪▒╪» ╪º┘ä╪¿╪┤╪▒┘è╪⌐ ┘ä╪¬╪¡╪│┘è┘å ╪º┘ä╪º╪│╪¬╪¼╪º╪¿╪⌐ ╪¿┘å╪│╪¿╪⌐ 25%.",
          "╪¿┘å╪º╪í ┘ç┘è┘â┘ä ╪¬┘å╪╕┘è┘à┘è ╪»┘è┘å╪º┘à┘è┘â┘è ╪▓╪º╪» ╪│╪▒╪╣╪⌐ ╪º┘ä╪¿╪¡╪½ 30%.",
          "╪¬╪¡╪│┘è┘å ╪º┘ä╪¿┘å┘è╪⌐ ╪º┘ä╪«┘ä┘ü┘è╪⌐ ┘ê╪«┘ü╪╢ ╪º┘ä╪¬┘â╪▒╪º╪▒ 15%.",
        ],
        stack: ["ASP.NET WebForms", "ADO.NET", "SQL Server"],
      },
      {
        title: "╪¬╪╖┘ê┘è╪▒ ASP.NET MVC - ╪¬╪»╪▒┘è╪¿ ╪¼╪º┘à╪╣┘è",
        company: "Al-Hussein Bin Talal University",
        period: "┘è┘ê┘ä┘è┘ê - ╪ú╪║╪│╪╖╪│ 2024",
        description: "╪¿┘ê╪º╪¿╪⌐ MVC ┘ä╪Ñ╪»╪º╪▒╪⌐ ┘à╪│╪º╪▒╪º╪¬ ╪¬╪»╪▒┘è╪¿ ╪º┘ä╪╖┘ä╪¿╪⌐ ┘ê┘à┘ê╪º┘ü┘é╪º╪¬ ╪º┘ä┘à╪┤╪▒┘ü┘è┘å.",
        highlights: [
          "╪¬┘é┘ä┘è┘ä ┘ê┘é╪¬ ┘à╪╣╪º┘ä╪¼╪⌐ ╪º┘ä╪¬┘é╪º╪▒┘è╪▒ 40% ╪¿╪º╪│╪¬╪«╪»╪º┘à ┘à╪╡╪º╪»┘é╪⌐ ╪ó┘à┘å╪⌐ ┘ê┘ç┘è┘â┘ä┘è╪⌐ Entity Framework ┘å╪╕┘è┘ü╪⌐.",
          "╪¬╪╖╪¿┘è┘é ╪╡┘ä╪º╪¡┘è╪º╪¬ ╪»┘è┘å╪º┘à┘è┘â┘è╪⌐ ╪¡╪│┘æ┘å╪¬ ┘â┘ü╪º╪í╪⌐ ╪º┘ä╪Ñ╪»╪º╪▒╪⌐ 20%.",
        ],
        stack: ["ASP.NET MVC", "Entity Framework", "SQL Server"],
      },
      {
        title: "┘å╪╕╪º┘à ╪Ñ╪»╪º╪▒╪⌐ ╪º┘ä┘ä┘è╪º┘é╪⌐ ┘ê╪º┘ä╪¬╪║╪░┘è╪⌐ ╪º┘ä┘à╪¬┘é╪»┘à",
        company: "Al-Hussein Bin Talal University",
        period: "┘ü╪¿╪▒╪º┘è╪▒ - ┘è┘ê┘å┘è┘ê 2024",
        description: "┘à╪┤╪▒┘ê╪╣ ╪¬╪«╪▒╪¼ ┘è┘é╪»┘à ╪¬╪¼╪▒╪¿╪⌐ ┘ä┘è╪º┘é╪⌐ ┘ê╪¬╪║╪░┘è╪⌐ ┘à╪¬╪╣╪»╪»╪⌐ ╪º┘ä┘à┘å╪╡╪º╪¬ (PureActive).",
        highlights: [
          "╪¿┘å╪º╪í ╪¬┘ê╪╡┘è╪º╪¬ ┘ê╪¼╪¿╪º╪¬ ╪┤╪«╪╡┘è╪⌐ ╪¬╪╣╪¬┘à╪» ┘à╪ñ╪┤╪▒/╪¡┘à┘ä ╪║┘ä╪º┘è╪│┘è┘à┘è ┘ä╪▒┘ü╪╣ ╪»┘é╪⌐ ╪º┘ä╪¬┘ê╪╡┘è╪⌐ 35%.",
          "╪¬┘à┘â┘è┘å ╪º┘ä┘à╪»╪▒╪¿┘è┘å ┘à┘å ╪Ñ┘å╪┤╪º╪í ╪«╪╖╪╖ ╪¬┘à╪▒┘è┘å ┘à╪«╪╡╪╡╪⌐ ╪▒┘ü╪╣ ╪º┘ä╪¬┘ü╪º╪╣┘ä ╪¿┘å╪¡┘ê 40%.",
          "┘ç┘å╪»╪│╪⌐ ┘à╪▓╪º┘à┘å╪⌐ ┘ä╪¡╪╕┘è╪⌐ ┘à╪╣ Firebase ┘ä╪¿┘è╪º┘å╪º╪¬ ╪│┘ä╪│╪⌐ ╪¿┘è┘å ╪º┘ä┘à┘å╪╡╪º╪¬.",
        ],
        stack: ["Flutter", "Dart", "Firebase", "SQLite"],
      },
    ],
    skills: {
      focusTitle: "┘à╪º ╪ú╪▒┘â╪▓ ╪╣┘ä┘è┘ç",
      technicalTitle: "╪º┘ä┘à┘â╪»╪│ ╪º┘ä╪¬┘é┘å┘è",
      mindsetTitle: "╪╖╪▒┘è┘é╪⌐ ╪º┘ä╪¬┘ü┘â┘è╪▒",
      focus: [
        "╪¬╪╡┘à┘è┘à ╪ú┘å╪╕┘à╪⌐ .NET ┘ä┘ä┘à╪º┘ä┘è╪⌐ ┘ê╪º┘ä┘à┘ê╪º╪▒╪» ╪º┘ä╪¿╪┤╪▒┘è╪⌐ ┘è┘à┘â┘å ╪º┘ä╪º╪╣╪¬┘à╪º╪» ╪╣┘ä┘è┘ç╪º.",
        "╪¬╪¡╪│┘è┘å ┘é┘ê╪º╪╣╪» ╪º┘ä╪¿┘è╪º┘å╪º╪¬ ┘ê┘à╪│╪º╪▒╪º╪¬ ╪º┘ä╪¬┘é╪º╪▒┘è╪▒.",
        "╪¬┘ê╪½┘è┘é ╪º┘ä┘à╪¬╪╖┘ä╪¿╪º╪¬ ┘ê╪º┘ä╪╡┘ä╪º╪¡┘è╪º╪¬ ╪¿┘ê╪╢┘ê╪¡.",
      ],
      technical: [
        { name: "C# / VB.NET / .NET", level: 90, detail: "╪¬╪╖┘ê┘è╪▒ ╪¬╪╖╪¿┘è┘é╪º╪¬ ╪│╪╖╪¡ ┘à┘â╪¬╪¿ ┘ê┘ê┘è╪¿ ┘à╪ñ╪│╪│┘è╪⌐." },
        { name: "ASP.NET MVC & WebForms", level: 88, detail: "┘ê╪º╪¼┘ç╪º╪¬ ┘à╪ñ╪│╪│┘è╪⌐ ┘à╪╣ ╪Ñ╪»╪º╪▒╪⌐ ╪╡┘ä╪º╪¡┘è╪º╪¬ ┘é┘ê┘è╪⌐." },
        { name: "WinForms & DevExpress", level: 85, detail: "╪┤╪º╪┤╪º╪¬ ┘à╪¡╪º╪│╪¿┘è╪⌐ ┘ê╪¬┘é╪º╪▒┘è╪▒ ╪¬┘ü╪º╪╣┘ä┘è╪⌐." },
        { name: "SQL Server", level: 87, detail: "╪¬╪¡╪│┘è┘å ╪º┘ä╪º╪│╪¬╪╣┘ä╪º┘à╪º╪¬ ┘ê╪¬╪╡┘à┘è┘à ╪º┘ä┘à╪«╪╖╪╖╪º╪¬." },
        { name: "Flutter & Firebase", level: 70, detail: "╪¬╪╖╪¿┘è┘é╪º╪¬ ╪╡╪¡╪⌐ ┘ê╪¬╪╣┘ä┘è┘à ┘à╪¬╪╣╪»╪»╪⌐ ╪º┘ä┘à┘å╪╡╪º╪¬." },
      ],
      mindset: ["╪¬╪¡╪│┘è┘å╪º╪¬ ┘à╪¿┘å┘è╪⌐ ╪╣┘ä┘ë ╪º┘ä╪¿┘è╪º┘å╪º╪¬", "╪¬╪╣╪º┘ê┘å ┘ä╪╡┘è┘é ┘à╪╣ ╪ú╪╡╪¡╪º╪¿ ╪º┘ä┘à╪╡┘ä╪¡╪⌐", "╪¬┘ê╪½┘è┘é ╪»┘é┘è┘é", "╪¡┘ä┘ê┘ä ╪º╪│╪¬╪¿╪º┘é┘è╪⌐"],
    },
    certificates: [
      {
        title: "╪¿┘â╪º┘ä┘ê╪▒┘è┘ê╪│ ┘ç┘å╪»╪│╪⌐ ╪º┘ä╪¿╪▒┘à╪¼┘è╪º╪¬",
        issuer: "╪¼╪º┘à╪╣╪⌐ ╪º┘ä╪¡╪│┘è┘å ╪¿┘å ╪╖┘ä╪º┘ä",
        year: "2024-09",
        summary: "╪»╪▒╪¼╪⌐ ╪º┘ä╪¿┘â╪º┘ä┘ê╪▒┘è┘ê╪│ ┘ü┘è ┘ç┘å╪»╪│╪⌐ ╪º┘ä╪¿╪▒┘à╪¼┘è╪º╪¬ ╪¿┘à╪╣╪»┘ä 74.36% ┘à╪╣ ╪¬╪▒┘â┘è╪▓ ╪╣┘ä┘ë ╪ú┘å╪╕┘à╪⌐ ╪º┘ä┘à╪ñ╪│╪│╪º╪¬ ┘ê┘é┘ê╪º╪╣╪» ╪º┘ä╪¿┘è╪º┘å╪º╪¬.",
        url: "",
      },
      {
        title: "Advanced Data Analytics",
        issuer: "USAID",
        year: "2025-06",
        summary: "┘à┘å┘ç╪¼ ╪¬╪¡┘ä┘è┘ä╪º╪¬ ╪¿┘è╪º┘å╪º╪¬ ┘à╪¬┘é╪»┘à╪⌐ ┘ä╪º╪¬╪«╪º╪░ ┘é╪▒╪º╪▒╪º╪¬ ╪º┘ä┘à┘å╪¬╪¼ ┘ê┘à╪ñ╪┤╪▒╪º╪¬ ╪º┘ä╪ú╪»╪º╪í ╪º┘ä╪¬╪┤╪║┘è┘ä┘è╪⌐.",
        url: "assets/Advanced%20Data%20Anlytics%20-%20USAID.pdf",
      },
      {
        title: "PostgreSQL",
        issuer: "Coursera",
        year: "2024-08",
        summary: "╪ú╪│╪º╪│┘è╪º╪¬ ╪¬╪╡┘à┘è┘à ┘ê╪º╪│╪¬╪╣┘ä╪º┘à ┘é┘ê╪º╪╣╪» ╪¿┘è╪º┘å╪º╪¬ PostgreSQL ┘à╪╣ ╪¬╪╖╪¿┘è┘é╪º╪¬ ╪╣┘à┘ä┘è╪⌐.",
        url: "assets/PostgreSQL.pdf",
      },
      {
        title: "HTML & CSS",
        issuer: "IBM SkillsBuild",
        year: "2024-08",
        summary: "╪ú╪│╪º╪│┘è╪º╪¬ ┘ê╪º╪¼┘ç╪º╪¬ ╪º┘ä┘ê┘è╪¿ ╪¬╪┤┘à┘ä ╪º┘ä╪¬╪«╪╖┘è╪╖ ┘ê╪º┘ä╪¬┘å╪│┘è┘é ┘ê╪Ñ┘à┘â╪º┘å┘è╪⌐ ╪º┘ä┘ê╪╡┘ê┘ä.",
        url: "assets/HTML%20%26%20CSS.pdf",
      },
      {
        title: "CV Writing and Interview",
        issuer: "USAID",
        year: "2024-07",
        summary: "╪Ñ╪▒╪┤╪º╪»╪º╪¬ ╪╣┘à┘ä┘è╪⌐ ┘ä╪╡┘è╪º╪║╪⌐ ╪º┘ä╪│┘è╪▒╪⌐ ╪º┘ä╪░╪º╪¬┘è╪⌐ ┘ê╪º┘ä╪º╪│╪¬╪╣╪»╪º╪» ┘ä┘ä┘à┘é╪º╪¿┘ä╪º╪¬ ╪º┘ä╪¬┘é┘å┘è╪⌐.",
        url: "assets/CV%20Writing%20And%20Interview.pdf",
      },
      {
        title: "C++ Foundations",
        issuer: "SoloLearn",
        year: "2022-12",
        summary: "╪ú╪│╪º╪│┘è╪º╪¬ ╪º┘ä╪¿╪▒┘à╪¼╪⌐ ┘â╪º╪ª┘å┘è╪⌐ ╪º┘ä╪¬┘ê╪¼┘ç ╪¿┘ä╪║╪⌐ ++C.",
        url: "assets/C++%20-%20SoloLearn.jpg",
      },
    ],
    caseStudies: [
      {
        title: "┘à┘å╪╡╪⌐ PureActive",
        period: "2024",
        summary: "╪¬╪¼╪▒╪¿╪⌐ ┘ä┘è╪º┘é╪⌐ ┘ê╪¬╪║╪░┘è╪⌐ ╪¬╪▒╪¿╪╖ ╪«╪╖╪╖ ╪º┘ä╪╖╪╣╪º┘à ╪¿╪º┘ä╪¬┘à╪º╪▒┘è┘å ┘ê╪¬╪»┘ü╪╣ ╪º┘ä╪¬╪¡┘ä┘è┘ä╪º╪¬ ┘ä┘ä┘à╪»╪▒╪¿┘è┘å ┘ä╪¡╪╕┘è┘ï╪º.",
        tags: ["Flutter", "Firebase", "Health Tech"],
        metrics: [
          { label: "╪»┘é╪⌐ ╪º┘ä╪¬┘ê╪╡┘è╪º╪¬", value: "35%+" },
          { label: "╪▒┘ü╪╣ ╪º┘ä╪¬┘ü╪º╪╣┘ä", value: "40%" },
        ],
      },
      {
        title: "╪┤╪º╪┤╪⌐ ╪º┘ä┘ç┘è┘â┘ä ╪º┘ä╪¬┘å╪╕┘è┘à┘è ┘ä┘ä┘à┘ê╪º╪▒╪» ╪º┘ä╪¿╪┤╪▒┘è╪⌐",
        period: "2024",
        summary: "╪┤╪º╪┤╪⌐ WebForms ╪»┘è┘å╪º┘à┘è┘â┘è╪⌐ ╪¬╪╡┘ê╪▒ ╪º┘ä┘ç┘è┘â┘ä ╪º┘ä╪¬┘å╪╕┘è┘à┘è ╪¿╪º╪│╪¬╪«╪»╪º┘à ╪¿┘è╪º┘å╪º╪¬ ╪º┘ä┘à┘ê╪º╪▒╪» ╪º┘ä╪¿╪┤╪▒┘è╪⌐ ╪º┘ä╪¡┘è╪⌐.",
        tags: ["ASP.NET WebForms", "ADO.NET", "UX"],
        metrics: [
          { label: "╪▓┘è╪º╪»╪⌐ ╪│╪▒╪╣╪⌐ ╪º┘ä╪¿╪¡╪½", value: "25%" },
          { label: "╪¬╪│┘ä┘è┘à ╪¿┘ä╪º ╪¬╪│┘ä┘è┘à╪º╪¬ ┘à╪╖┘ê┘ä╪⌐", value: "0 handoffs" },
        ],
      },
      {
        title: "┘à┘ê╪▓┘ê┘å ┘ä┘ä┘à╪¡╪º╪│╪¿╪⌐",
        period: "2025",
        summary: "╪¡╪▓┘à╪⌐ ╪│╪╖╪¡ ┘à┘â╪¬╪¿ ╪¬╪»┘è╪▒ ╪ú┘å┘ê╪º╪╣ ╪º┘ä┘é┘è┘ê╪» ┘ê╪º┘ä╪¡╪│╪º╪¿╪º╪¬ ┘ê╪º┘ä╪¬┘é╪º╪▒┘è╪▒ ╪º┘ä┘à╪º┘ä┘è╪⌐ ╪º┘ä┘à╪ñ╪¬┘à╪¬╪⌐.",
        tags: ["WinForms", "SQL Server", "Crystal Reports"],
        metrics: [
          { label: "╪«┘ü╪╢ ╪º┘ä╪╣┘à┘ä ╪º┘ä┘è╪»┘ê┘è", value: "35%" },
          { label: "╪¬┘ê┘ü┘è╪▒ ╪▓┘à┘å ╪º┘ä╪¬┘é╪º╪▒┘è╪▒", value: "30%" },
        ],
      },
      {
        title: "╪º┘ä╪¬┘â╪╣┘è╪¿ ╪º┘ä┘à╪╣┘à╪º╪▒┘è",
        period: "2025",
        summary: "┘à┘å╪╡╪⌐ ╪¬┘ê╪▒┘è╪» ╪▒╪│┘à┘è╪⌐ ┘ä┘à┘ê╪º╪» ╪º┘ä╪¿┘å╪º╪í (╪ú╪«╪┤╪º╪¿╪î ╪¡╪»┘è╪» ╪¬╪│┘ä┘è╪¡╪î ╪╣╪▓┘ä ┘ê╪¬╪¼┘ç┘è╪▓╪º╪¬) ╪¿╪«╪╖┘ê╪º╪¬ ┘ê╪º╪╢╪¡╪⌐╪î ╪¬╪│╪╣┘è╪▒ ┘à┘ê╪½┘é╪î ┘ê╪¬┘ê╪º╪╡┘ä ┘à┘ê╪¡┘æ╪» ╪¡╪¬┘ë ╪º┘ä╪¬╪│┘ä┘è┘à.",
        tags: ["┘à┘å╪╡╪⌐ ╪¬┘ê╪▒┘è╪»", "╪¬╪¼╪▒╪¿╪⌐ ╪╣╪▒╪¿┘è╪⌐", "┘ê╪º╪¼┘ç╪⌐ ╪¬┘ü╪º╪╣┘ä┘è╪⌐"],
        metrics: [
          { label: "╪╣╪▒╪╢ ┘à╪¿╪º╪┤╪▒", value: "Web demo" },
          { label: "╪º┘ä╪¬╪╡┘è┘è╪▒", value: "WebGL" },
        ],
        link: "https://wsma15.github.io/ArchitecturalCubism/",
      },
    ],
    lab: [
      {
        title: "╪º┘ä╪º╪│╪¬┘â╪┤╪º┘ü",
        description: "┘ä┘é╪º╪í ╪ú╪╡╪¡╪º╪¿ ╪º┘ä┘à╪╡┘ä╪¡╪⌐╪î ┘à╪▒╪º╪¼╪╣╪⌐ ╪º┘ä╪¿┘è╪º┘å╪º╪¬ ╪º┘ä┘à┘ê╪▒┘ê╪½╪⌐╪î ┘ê╪¬╪¡╪»┘è╪» ┘à╪╣╪º┘è┘è╪▒ ╪º┘ä┘å╪¼╪º╪¡.",
        actions: ["┘ê╪▒╪┤ ╪╣┘à┘ä ┘à╪╣ ╪ú╪╡╪¡╪º╪¿ ╪º┘ä┘à╪╡┘ä╪¡╪⌐", "┘à╪▒╪º╪¼╪╣╪⌐ ╪º┘ä╪¿┘è╪º┘å╪º╪¬ ┘ê╪º┘ä╪¼╪»╪º┘ê┘ä", "╪¬╪¡╪»┘è╪» ┘à╪ñ╪┤╪▒╪º╪¬ ╪º┘ä╪ú╪»╪º╪í ┘ê╪º┘ä╪╢┘ê╪º╪¿╪╖"],
      },
      {
        title: "╪¬╪╡┘à┘è┘à ┘é╪º╪╣╪»╪⌐ ╪º┘ä╪¿┘è╪º┘å╪º╪¬",
        description: "┘å┘à╪░╪¼╪⌐ ╪º┘ä┘â┘è╪º┘å╪º╪¬ ┘ê╪º┘ä┘é┘è┘ê╪» ┘ê╪º┘ä╪╡┘ä╪º╪¡┘è╪º╪¬ ┘à╪╣ ┘à╪▒╪º╪╣╪º╪⌐ ╪º┘ä╪¬┘ê╪│╪╣.",
        actions: ["┘à╪«╪╖╪╖╪º╪¬ ER", "╪│┘è╪º╪│╪º╪¬ ╪╡┘ä╪º╪¡┘è╪º╪¬", "╪¬┘ç┘è╪ª╪⌐ ┘å┘à╪º╪░╪¼ Entity Framework"],
      },
      {
        title: "╪¬┘å┘ü┘è╪░ .NET",
        description: "╪¿┘å╪º╪í ╪º┘ä┘ê╪º╪¼┘ç╪⌐ ┘ê╪º┘ä┘ê╪º╪¼┘ç╪º╪¬ ╪º┘ä╪¿╪▒┘à╪¼┘è╪⌐╪î ╪»┘à╪¼ ╪º┘ä╪¬┘é╪º╪▒┘è╪▒╪î ┘ê╪▒╪¿╪╖ ╪º┘ä╪▒╪│╪º╪ª┘ä ╪ú┘ê ╪º┘ä╪¿╪▒┘è╪».",
        actions: ["┘à┘â┘ê┘å╪º╪¬ ┘é╪º╪¿┘ä╪⌐ ┘ä╪Ñ╪╣╪º╪»╪⌐ ╪º┘ä╪º╪│╪¬╪«╪»╪º┘à", "Crystal Reports", "╪º╪«╪¬╪¿╪º╪▒╪º╪¬ ╪¬┘â╪º┘à┘ä"],
      },
      {
        title: "╪╢┘à╪º┘å ╪º┘ä╪¼┘ê╪»╪⌐ ┘ê╪º┘ä╪¬╪│┘ä┘è┘à",
        description: "╪º╪«╪¬╪¿╪º╪▒╪º╪¬ ┘é╪¿┘ê┘ä╪î ┘å┘é┘ä ┘à╪╣╪▒┘ü╪⌐╪î ┘ê╪»╪╣┘à ┘à╪º ╪¿╪╣╪» ╪º┘ä╪Ñ╪╖┘ä╪º┘é.",
        actions: ["┘é┘ê╪º╪ª┘à ╪¬╪¡┘é┘é QA", "╪ú╪»┘ä╪⌐ ┘ü┘è╪»┘è┘ê ╪│╪▒┘è╪╣╪⌐", "┘à╪¬╪º╪¿╪╣╪⌐ ┘à╪º ╪¿╪╣╪» ╪º┘ä╪Ñ╪╖┘ä╪º┘é"],
      },
    ],
    contact: {
      labels: { email: "╪º┘ä╪¿╪▒┘è╪» ╪º┘ä╪Ñ┘ä┘â╪¬╪▒┘ê┘å┘è", phone: "╪º┘ä┘ç╪º╪¬┘ü", whatsapp: "┘ê╪º╪¬╪│╪º╪¿", city: "╪º┘ä┘à┘ê┘é╪╣", socials: "╪▒┘ê╪º╪¿╪╖" },
      email: "hussein.alwisi@outlook.com",
      phone: "+962 790119021",
      whatsapp: "+962 790119021",
      whatsappMessage: "╪ú┘ç┘ä┘ï╪º ╪¡╪│┘è┘å╪î ╪ú┘ê╪» ┘à┘å╪º┘é╪┤╪⌐ ┘à╪┤╪▒┘ê╪╣ .NET ╪¿╪«╪╡┘ê╪╡ ...",
      city: "╪Ñ╪▒╪¿╪»╪î ╪º┘ä╪ú╪▒╪»┘å | ╪╣┘à┘ä ╪╣┘å ╪¿╪╣╪» ╪ú┘ê ┘ç╪¼┘è┘å ╪ú┘ê ╪¡╪╢┘ê╪▒┘è",
      socials: [
        { label: "GitHub", url: "https://github.com/wsma15" },
        { label: "LinkedIn", url: "https://www.linkedin.com/in/hussein-alwisi/" },
        { label: "Facebook", url: "https://web.facebook.com/0wsma15" },
      ],
      form: {
        labels: { name: "╪º┘ä╪º╪│┘à ╪º┘ä┘â╪º┘à┘ä", email: "╪º┘ä╪¿╪▒┘è╪» ╪º┘ä╪Ñ┘ä┘â╪¬╪▒┘ê┘å┘è", type: "┘å┘ê╪╣ ╪º┘ä┘à╪┤╪▒┘ê╪╣", message: "┘à┘ä╪«╪╡ ╪º┘ä┘à╪┤╪▒┘ê╪╣" },
        placeholders: {
          name: "┘à╪½╪º┘ä: ╪╣╪¿╪»╪º┘ä┘ä┘ç ╪º┘ä╪│╪º┘ä┘à",
          email: "you@email.com",
          message: "╪┤╪º╪▒┘â ╪º┘ä┘ç╪»┘ü ┘ê╪º┘ä┘å╪╖╪º┘é ┘ê╪º┘ä┘à┘ê╪╣╪» ╪º┘ä┘à╪¬┘ê┘é╪╣",
        },
        options: {
          default: "╪º╪«╪¬╪▒ ┘å┘ê╪╣ ╪º┘ä┘à╪┤╪▒┘ê╪╣",
          website: "╪¬╪╖╪¿┘è┘é ┘ê┘è╪¿ / ╪│╪╖╪¡ ┘à┘â╪¬╪¿",
          consulting: "╪º╪│╪¬╪┤╪º╪▒╪º╪¬ .NET ╪ú┘ê ┘é┘ê╪º╪╣╪» ╪¿┘è╪º┘å╪º╪¬",
          workshop: "┘ê╪▒╪┤╪⌐ ╪╣┘à┘ä / ╪¬╪»╪▒┘è╪¿",
        },
        button: "╪ú╪▒╪│┘ä ╪º┘ä╪╖┘ä╪¿",
        note: "╪¿┘è╪º┘å╪º╪¬┘â ╪¬╪¿┘é┘ë ╪«╪º╪╡╪⌐. ╪│┘è╪╡┘ä┘â ╪▒╪» ╪«┘ä╪º┘ä 24 ╪│╪º╪╣╪⌐.",
        success: "╪┤┘â╪▒┘ï╪º {{name}}! ╪│╪ú╪¬┘ê╪º╪╡┘ä ┘à╪╣┘â ╪«┘ä╪º┘ä 24 ╪│╪º╪╣╪⌐.",
      },
    },
  },
  en: {
    pageTitle: "Hussein Alwisi .NET Software Engineer",
    hero: {
      name: "Hussein Alwisi",
      brandMark: "H",
      brandTagline: ".NET Software Engineer",
      footerRole: ".NET Software Engineer",
      title: ".NET Software Engineer",
      location: "Irbid, Jordan",
      availability: "Open to full-time .NET opportunities",
      metaLabels: { location: "Location", availability: "Availability" },
      bio: "Detail-oriented software engineer building secure and scalable desktop/web apps in the Microsoft .NET ecosystem with a focus on financial systems, HR tooling, and Crystal Reports automation.",
      cvUrl: "assets/HusseinAlwisiResume.pdf",
      ctas: { primary: "Download Resume", secondary: "Let's talk" },
      photo: "assets/Me.jpeg",
      photoAlt: "Hussein Alwisi portrait",
      chips: [
        "C# / VB.NET",
        "WinForms & DevExpress",
        "ASP.NET MVC / WebForms",
        "SQL Server & EF",
        "Crystal Reports Automation",
      ],
      dynamicRoles: ["Builds reliable accounting tools", "Ships enterprise .NET apps", "Automates financial reporting"],
      clientsHeading: "Teams I've supported",
      clients: ["Mozon Accounting", "HR Org Builder", "Attachments", "PureActive"],
      score: 35,
      scoreSuffix: "%",
      scoreLabel: "Ops acceleration",
      scoreCaption: "Average manual effort reduced inside key flows",
    },
    copy: {
      nav: {
        ariaLabel: "Primary navigation",
        home: "Home",
        impact: "Impact",
        experience: "Experience",
        skills: "Skills",
        certificates: "Certifications",
        work: "Case Studies",
        lab: "Process Lab",
        contact: "Contact",
        cta: "Let's talk",
      },
      sections: {
        impact: {
          eyebrow: "Measurable wins",
          title: "Numbers that back decisions",
          description:
            "Every initiative I touch has a measurable KPIΓÇöfrom accounting automation to student portals. These are the latest stats from Mozon and university projects.",
        },
        experience: {
          eyebrow: "Career track",
          title: "Hands-on delivery",
          description:
            "I move between desktop and web stacks, model databases, coach QA, and ship products that remain maintainable for internal teams.",
        },
        skills: {
          eyebrow: "Skill matrix",
          title: "Technical depth + ownership",
          description:
            "Modern .NET practices, optimized SQL, and a product mindset to keep stakeholders aligned and confident.",
        },
        certificates: {
          eyebrow: "Credentials",
          title: "Verified learning",
          description: "Selected courses and certificates that strengthen my .NET, database, and communication work.",
          cta: "View certificate",
        },
        work: {
          eyebrow: "Case studies",
          title: "Projects that solved real pain",
          description:
            "Selected work spanning accounting suites, HR tooling, and a cross-platform wellness platform.",
          controls: { prev: "Previous project", next: "Next project" },
          viewProject: "View project",
        },
        lab: {
          eyebrow: "Process lab",
          title: "How I approach delivery",
          description:
            "From discovery to QA handover, each step keeps stakeholders involved and data flowing into the right dashboards.",
        },
        contact: {
          eyebrow: "Quick contact path",
          title: "Let's start a conversation",
          description:
            "Need a reliable .NET dev for your accounting product or HR module? Share the details and I'll respond within a day.",
        },
      },
      labDetail: { eyebrow: "Stage details" },
      footer: {
        primary: "┬⌐ {year} All rights reserved.",
        secondary: "Building purposeful software.",
      },
    },
    stats: [
      {
        label: "Years of hands-on experience",
        value: 2,
        suffix: "+",
        description: "Two years of shipping .NET systems across finance, HR, and education products.",
      },
      {
        label: "Manual journal prep saved",
        value: 35,
        suffix: "%",
        description: "Automated chart of accounts routines inside the Mozon accounting suite.",
      },
      {
        label: "Faster financial reporting",
        value: 30,
        suffix: "%",
        description: "Crystal Reports templating delivers ready-to-export statements instantly.",
      },
      {
        label: "HR lookup efficiency gain",
        value: 30,
        suffix: "%",
        description: "The dynamic org-chart builder lets HR locate people and divisions 30% faster.",
      },
      {
        label: "Internship review cycle faster",
        value: 40,
        suffix: "%",
        description: "Role-based workflows in the MVC internship portal shorten the report-review cycle from weeks to days.",
      },
    ],
    experiences: [
      {
        title: "Medu (Mozon Education) - Attachments & Workflow",
        company: "Mozon Technology",
        period: "Jul 2025 - Dec 2025",
        description:
          "Led ASP.NET Windows Forms delivery for Medu's attachment management and approval workflows.",
        highlights: [
          "Built secure attachment management with upload, preview, download, and delete for student/system documents.",
          "Implemented document-type permissions, refined the UI, addressed test issues, and shipped activation + development guides.",
          "Delivered workflow types, approvals, and My Requests / My Approvals screens with a flexible multi-step approval engine.",
        ],
        stack: ["C#", "WinForms", "SQL Server", "Crystal Reports"],
      },
      {
        title: "Accounting System - ASP.NET Windows Forms",
        company: "Mozon Technology",
        period: "Dec 2024 - May 2025",
        description: "Owned accounting modules and reporting performance improvements.",
        highlights: [
          "Delivered journal types, journal entries, account types, and a dynamic chart of accounts.",
          "Cut manual processing by 35% through optimized forms and database integration.",
          "Integrated SAP Crystal Reports (30% faster prep) and tuned SQL for ~20% quicker retrieval.",
        ],
        stack: ["C#", "WinForms", "SQL Server", "Crystal Reports"],
      },
      {
        title: "ASP.NET WebForms Development - Internship",
        company: "Mozon Technology",
        period: "Sep - Nov 2024",
        description: "Refreshed HR WebForms screens and data structures during internship.",
        highlights: [
          "Modernized HR UI to improve responsiveness by 25%.",
          "Built a dynamic organizational chart that increased lookup efficiency by 30%.",
          "Improved backend structure, reducing data redundancy by 15%.",
        ],
        stack: ["ASP.NET WebForms", "ADO.NET", "SQL Server"],
      },
      {
        title: "ASP.NET MVC Development - University Internship",
        company: "Al-Hussein Bin Talal University",
        period: "Jul - Aug 2024",
        description: "MVC portal for managing university internship workflows and supervisor approvals.",
        highlights: [
          "Reduced report processing time by 40% using secure authentication and clean Entity Framework architecture.",
          "Implemented dynamic role-based access that improved administrative efficiency by 20%.",
        ],
        stack: ["ASP.NET MVC", "Entity Framework", "SQL Server"],
      },
      {
        title: "Advanced Fitness & Nutrition Management Software",
        company: "Al-Hussein Bin Talal University",
        period: "Feb - Jun 2024",
        description: "Graduation project delivering a cross-platform fitness and nutrition experience (PureActive).",
        highlights: [
          "Built personalized meal planning with glycemic index/load to improve recommendation accuracy by 35%.",
          "Enabled trainers to create custom workout routines, lifting engagement by ~40%.",
          "Engineered real-time sync with Firebase for seamless cross-platform data.",
        ],
        stack: ["Flutter", "Dart", "Firebase", "SQLite"],
      },
    ],
    skills: {
      focusTitle: "What I focus on",
      technicalTitle: "Technical stack",
      mindsetTitle: "Mindset",
      focus: [
        "Designing dependable .NET finance/HR systems.",
        "Optimizing databases and reporting workflows.",
        "Documenting requirements and permissions clearly.",
      ],
      technical: [
        { name: "C# / VB.NET / .NET", level: 90, detail: "Desktop and web application development." },
        { name: "ASP.NET MVC & WebForms", level: 88, detail: "Enterprise UI with solid role management." },
        { name: "WinForms & DevExpress", level: 85, detail: "Accounting screens and interactive reports." },
        { name: "SQL Server", level: 87, detail: "Query optimization and schema design." },
        { name: "Flutter & Firebase", level: 70, detail: "Cross-platform health/education apps." },
      ],
      mindset: [
        "Data-driven improvements",
        "Close stakeholder collaboration",
        "Thorough documentation",
        "Proactive problem solving",
      ],
    },
    certificates: [
      {
        title: "B.Sc. Software Engineering",
        issuer: "Al-Hussein Bin Talal University",
        year: "2024-09",
        summary: "Bachelor's degree in Software Engineering (GPA 74.36%) focused on enterprise systems and databases.",
        url: "",
      },
      {
        title: "Advanced Data Analytics",
        issuer: "USAID",
        year: "2025-06",
        summary: "Advanced analytics curriculum for product decisions and operational KPIs.",
        url: "assets/Advanced%20Data%20Anlytics%20-%20USAID.pdf",
      },
      {
        title: "PostgreSQL",
        issuer: "Coursera",
        year: "2024-08",
        summary: "Foundations of designing and querying PostgreSQL databases with hands-on labs.",
        url: "assets/PostgreSQL.pdf",
      },
      {
        title: "HTML & CSS",
        issuer: "IBM SkillsBuild",
        year: "2024-08",
        summary: "Web interface basics covering layout, styling, and accessibility.",
        url: "assets/HTML%20%26%20CSS.pdf",
      },
      {
        title: "CV Writing and Interview",
        issuer: "USAID",
        year: "2024-07",
        summary: "Practical guidance for crafting resumes and preparing for technical interviews.",
        url: "assets/CV%20Writing%20And%20Interview.pdf",
      },
      {
        title: "C++ Foundations",
        issuer: "SoloLearn",
        year: "2022-12",
        summary: "Object-oriented programming fundamentals in C++.",
        url: "assets/C++%20-%20SoloLearn.jpg",
      },
    ],
    caseStudies: [
      {
        title: "PureActive Platform",
        period: "2024",
        summary:
          "Fitness + nutrition experience syncing food plans with workouts and pushing insights to trainers instantly.",
        tags: ["Flutter", "Firebase", "Health Tech"],
        metrics: [
          { label: "Recommendation accuracy", value: "35%+" },
          { label: "User engagement lift", value: "40%" },
        ],
      },
      {
        title: "HR Org Chart Screen",
        period: "2024",
        summary: "Dynamic WebForms screen that visualizes the organization using live HR data.",
        tags: ["ASP.NET WebForms", "ADO.NET", "UX"],
        metrics: [
          { label: "Lookup speed gain", value: "25%" },
          { label: "Updates required devs", value: "0 handoffs" },
        ],
      },
      {
        title: "Mozon Accounting",
        period: "2025",
        summary: "Desktop suite that manages journal types, accounts, and automated financial statements.",
        tags: ["WinForms", "SQL Server", "Crystal Reports"],
        metrics: [
          { label: "Manual work reduced", value: "35%" },
          { label: "Reporting time saved", value: "30%" },
        ],
      },
      {
        title: "Architectural Cubism",
        period: "2025",
        summary: "Official supply platform for timber, steel, insulation, and fit-out materials with documented pricing, unified communication, and clear delivery steps.",
        tags: ["Supply platform", "Arabic UX", "WebGL experience"],
        metrics: [
          { label: "Live showcase", value: "Web demo" },
          { label: "Rendering", value: "WebGL" },
        ],
        link: "https://wsma15.github.io/ArchitecturalCubism/",
      },
    ],
    lab: [
      {
        title: "Discovery",
        description: "Interview stakeholders, audit spreadsheets, and define success metrics.",
        actions: ["Stakeholder workshops", "Legacy data review", "KPIs and guardrails"],
      },
      {
        title: "Database design",
        description: "Model entities, constraints, and permissions with scalability in mind.",
        actions: ["ER diagrams", "Permission policies", "EF model prep"],
      },
      {
        title: ".NET implementation",
        description: "Ship the UI/APIs, integrate reports, and wire up messaging or email.",
        actions: ["Reusable components", "Crystal reporting", "Integration tests"],
      },
      {
        title: "QA & handover",
        description: "Acceptance testing, knowledge transfer, and post-launch support.",
        actions: ["QA checklists", "Quick video guides", "Post-launch follow-up"],
      },
    ],
    contact: {
      labels: { email: "Email", phone: "Phone", whatsapp: "WhatsApp", city: "Location", socials: "Social" },
      email: "hussein.alwisi@outlook.com",
      phone: "+962 790119021",
      whatsapp: "+962 790119021",
      whatsappMessage: "Hi Hussein, I'd like to discuss a .NET project about ...",
      city: "Irbid, Jordan - Remote, hybrid, or onsite",
      socials: [
        { label: "GitHub", url: "https://github.com/wsma15" },
        { label: "LinkedIn", url: "https://www.linkedin.com/in/hussein-alwisi/" },
        { label: "Facebook", url: "https://web.facebook.com/0wsma15" },
      ],
      form: {
        labels: { name: "Full name", email: "Email", type: "Project type", message: "Project summary" },
        placeholders: {
          name: "e.g. Abdullah Al Salem",
          email: "you@email.com",
          message: "Share the goal, scope, and target date",
        },
        options: {
          default: "Select a project type",
          website: "Web / desktop application",
          consulting: ".NET or database consulting",
          workshop: "Workshop / training support",
        },
        button: "Send request",
        note: "Your information stays private. Expect a reply within 24 hours.",
        success: "Thanks {{name}}! I'll get back to you within 24 hours.",
      },
    },
  },
};
